# Generated by Django 5.2.8 on 2025-12-05 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_v', models.FloatField(default=1.0, help_text='Left eye visual acuity')),
                ('right_v', models.FloatField(default=1.0, help_text='Right eye visual acuity')),
                ('left_d', models.FloatField(default=0.0, help_text='Left eye diopter')),
                ('right_d', models.FloatField(default=0.0, help_text='Right eye diopter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vision_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Vision Data',
                'verbose_name_plural': 'User Vision Data',
            },
        ),
    ]
