# Generated by Django 6.0.3 on 2026-03-14 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0003_studyplan_studyschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer'), ('long', 'Long Answer'), ('essay', 'Essay'), ('problem', 'Problem Solving')], max_length=20)),
                ('question_text', models.TextField()),
                ('topic', models.CharField(help_text='Topic/Chapter this question belongs to', max_length=200)),
                ('marks', models.IntegerField(default=5)),
                ('frequency_count', models.IntegerField(default=1, help_text='How many times this topic appeared')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very Hard')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_exam_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'subject', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='SmartRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('next_review', models.DateField()),
                ('review_count', models.IntegerField(default=0)),
                ('interval_days', models.IntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days'), (7, '1 week'), (14, '2 weeks'), (30, '1 month'), (60, '2 months')], default=1)),
                ('ease_factor', models.FloatField(default=2.5, help_text='SM-2 algorithm ease factor')),
                ('is_mastered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='RevisionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('quality', models.IntegerField(choices=[(0, 'Complete blackout'), (1, 'Incorrect response, correct one remembered'), (2, 'Incorrect response, easy to recall correct'), (3, 'Correct with serious difficulty'), (4, 'Correct with hesitation'), (5, 'Perfect response')], default=3)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='visionapp.smartrevision')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
