# Generated by Django 5.2.8 on 2026-03-14 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0005_doubtsession_doubtmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='notes_uploads/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File'), ('image', 'Image')], max_length=20)),
                ('short_notes', models.TextField(help_text='Concise summary notes')),
                ('key_points', models.JSONField(default=list, help_text='List of key points')),
                ('important_definitions', models.JSONField(default=list, help_text='Key definitions extracted')),
                ('formulas', models.JSONField(default=list, help_text='Formulas and equations')),
                ('mind_map_data', models.JSONField(default=dict, help_text='Mind map structure in JSON')),
                ('mind_map_svg', models.TextField(blank=True, help_text='SVG representation of mind map')),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from file')),
                ('page_count', models.IntegerField(default=1)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Notes',
                'verbose_name_plural': 'Generated Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MindMapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (0 = root)')),
                ('color', models.CharField(default='#667eea', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mind_map_nodes', to='visionapp.generatednotes')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='visionapp.mindmapnode')),
            ],
        ),
    ]
